name: link22_o
description: This is the prototype of Project Link 22.O

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter_screenutil: ^5.3.1
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.12
  cloud_firestore: ^3.1.10
  firebase_core: ^1.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_bacground: "03A9F4"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pics/
    - assets/pics/details_1a.jpg